export const CONNECT_WALLET = "CONNECT_WALLET";

export const SET_CONTRACT_LOADING = "SET_CONTRACT_LOADING";
export const INITIALIZE_CONTRACT = "INITIALIZE_CONTRACT";
export const CONTRACT_SUCCESS = "CONTRACT_SUCCESS";
export const CONTRACT_ERROR = "CONTRACT_ERROR";

export const SET_DATA_LOADING = "SET_DATA_LOADING";
export const GET_DATA = "GET_DATA";
export const DATA_SUCCESS = "DATA_SUCCESS";
export const DATA_ERROR = "DATA_ERROR";

export const SEND_BID = "SEND_BID";
export const BID_SUCCESS = "BID_SUCCESS";
export const BID_ERROR = "BID_ERROR";

export const SEND_COLLECT = "SEND_COLLECT";
export const COLLECT_SUCCESS = "COLLECT_SUCCESS";
export const COLLECT_ERROR = "COLLECT_ERROR";

export const RESET_DAPP = "RESET_DAPP";
